[2024-11-02T11:21:06.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T11:21:06.158+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_V3.get_name manual__2024-11-02T11:21:05.156981+00:00 [queued]>
[2024-11-02T11:21:06.171+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_V3.get_name manual__2024-11-02T11:21:05.156981+00:00 [queued]>
[2024-11-02T11:21:06.172+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-11-02T11:21:06.225+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): get_name> on 2024-11-02 11:21:05.156981+00:00
[2024-11-02T11:21:06.245+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1407) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-02T11:21:06.246+0000] {standard_task_runner.py:72} INFO - Started process 1412 to run task
[2024-11-02T11:21:06.248+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_V3', 'get_name', 'manual__2024-11-02T11:21:05.156981+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python.py', '--cfg-path', '/tmp/tmpdc6l4jnq']
[2024-11-02T11:21:06.250+0000] {standard_task_runner.py:105} INFO - Job 140: Subtask get_name
[2024-11-02T11:21:06.351+0000] {task_command.py:467} INFO - Running <TaskInstance: our_dag_with_python_operator_V3.get_name manual__2024-11-02T11:21:05.156981+00:00 [running]> on host 8ad119be1b6a
[2024-11-02T11:21:06.511+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='johnwell' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_V3' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T11:21:05.156981+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T11:21:05.156981+00:00'
[2024-11-02T11:21:06.511+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T11:21:06.604+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-02T11:21:06.634+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T11:21:06.634+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_dag_with_python_operator_V3, task_id=get_name, run_id=manual__2024-11-02T11:21:05.156981+00:00, execution_date=20241102T112105, start_date=20241102T112106, end_date=20241102T112106
[2024-11-02T11:21:06.677+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T11:21:06.725+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T11:21:06.740+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
